### ISSUE TITLE
Codecov handling

### ISSUE THREAD

**Issue by erikbosch** [eclipse-kuksa/kuksa-databroker#11]
We use [codecov](https://github.com/codecov/codecov-action), see https://github.com/eclipse-kuksa/kuksa-databroker/blob/main/.github/workflows/kuksa_databroker_build.yml

Some problems observed:

```
      - name: Upload coverage to Codecov
        # To use v4 a token must be specifed by "token: ${{ secrets.CODECOV_TOKEN }}""
        # Uploaded result available at https://app.codecov.io/gh/eclipse-kuksa/kuksa-databroker
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
```

- We use an old version, so we get warnings on Node.js
- By using the old version upload often fail, a known problem, see https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
- To use the new version we need a token in the eclipse-kuksa orga setup.
- We also do not fail if upload fails, possible we should have settings like in [old repo](https://github.com/eclipse/kuksa.val/blob/master/.github/workflows/kuksa_val_unittest.yml)
```

      uses: codecov/codecov-action@v3
      with:
        files: ${{github.workspace}}/out/all_targets.info
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
```
